info:
  name: Get roles
  type: http
  seq: 1

http:
  method: GET
  url: http://localhost:3000/api/roles
  params:
    - name: search
      value: admin
      type: query
      disabled: true
    - name: search
      value: comun
      type: query
      disabled: true
    - name: search
      value: sistema
      type: query
      disabled: true
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
